[package]
name = "findit-rs"
version = "0.2.5"
edition = "2024"
description = "A fast, lightweight command-line filesystem search tool"
license = "MIT"
repository = "https://github.com/LukachuPro88/findit"
readme = "README.md"
documentation = "https://docs.rs/findit-rs"

[[bin]]
name = "findit"
path = "src/main.rs"

[dependencies]
eframe = "0.34.2"
